### ISSUE TITLE
Definition of "Measures" in MIND

### ISSUE THREAD

**Issue by aleph9999** [randel/MIND#1]
I am interested in applying this tool to other datasets. However the "measure" required for this tool is still unclear for me. 
For example, in a triplicate sample with 2 groups (total 6 samples). Should I format the sample into the matrix below or something differently? 
"1"
Gene * (group1_1, group2_1) 
"2"
Gene * (group1_2, group2_2) 
"3"
Gene * (group1_3, group2_3) 

In addition, are these triplicates interchangeable? For common bulk analysis information for which sample were measured together is not available, can I randomly assign measures label in such case? Thanks for response!

**Comment by randel** [comment]
Thanks for your interest!  "Measures" are defined as multiple samples per subject.  For instance, it can be multiple brain regions or repeated measures of the same tissue.  The multiple measures share common cell types and thus can be deconvolved together.

For the input, `X` is assumed to be a 3D array, gene by subject by measure.  If I understand correctly, your `group` can be regarded as `subject`, and `triplicates` can be regarded as `measures`.  If so, your format seems correct.  Of course, we need the number of `subjects` to be large enough to obtain meaningful results.
X: bulk gene expression (gene x subject x measure).
W: subject-specific cell type fraction (subject x measure x cell type)

Yes, different `measures` are interchangeable, as long as they are matched with the order in `W`.
