### ISSUE TITLE
extract brain tissue from gtex gene count

### ISSUE THREAD

**Issue by ketkijoshi278** [randel/MIND#10]
Hello,
I have downloaded GTEx rna-seq data from this site:
wget https://storage.googleapis.com/gtex_analysis_v8/rna_seq_data/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct.gz
I want to extract only brain tissue gene expression data from this file.
I checked yarn package and does it has any function that can perform this function?
Can you please provide me some guidance on how to proceed with this?
Thank you

**Comment by randel** [comment]
This question is not related to (b)MIND, but we have an example below.
https://randel.github.io/MIND/reference/est_frac.html

Using SMTS == 'Brain' in GTEx_v7_Annotations_SampleAttributesDS.txt, we can extract brain tissue id (SAMPID) from GTEx data.
