### ISSUE TITLE
This package cannot work normally!

### ISSUE THREAD

**Issue by BiaoCai1993** [randel/MIND#11]
This package is quite useful and I really like this paper. However, it cannot work well in the recent update. When I run the example of bmind_de function, it show the following error. Hope it can be fixed. Thanks!

[1] "12 errors"
List of 1
 $ :List of 2
  ..$ message: chr "could not find function \"bmind1_y\""
  ..$ call   : language bmind1_y(X[j, ], W, y, max_samp = max_samp, np = np, nu = nu, noRE = noRE, covariate = covariate, covariate_bulk | __truncated__
  ..- attr(*, "class")= chr [1:3] "simpleError" "error" "condition"
NULL
Error in apply(pval, 2, function(x) p.adjust(x, method = "fdr")) : 
  dim(X) must have a positive length

**Comment by randel** [comment]
Thanks for your interest. I tested it on my side but cannot replicate the error. Can you restart R/Rstudio or re-install the MIND package to check again? Or did you have `bmind1_y()` in your environment?

**Comment by BiaoCai1993** [comment]
Dear Prof. Wang,

I check the code again. It seems the issue is from foreach. In the foreach
part, it cannot attach bmind1_y function. If I change bmind1_y to
MIND::bmind1_y, this problem can be solved. Hope others do not have similar
problems.

Best regards,
Biao

**Comment by randel** [comment]
Thanks for your response. I think it may be fine given `foreach` is loaded in the MIND package. Let's see if others have the same issue.
