### ISSUE TITLE
Error running bmind_de

### ISSUE THREAD

**Issue by 99fatimagr** [randel/MIND#12]
Hi, thank you for this package! Similar to other posters I also have only a few samples in the single cell dataset (10 total, 4 and 6 in each group) and get a non-positive definite matrix when I call get_prior. I used the new version of get_prior and set filter_pd = F and then it works. I then use the results of get_prior and get an error when I call bmind_de though, below. Could you help me figure out what's going wrong? Thanks, Fatima

 "56564 errors"
List of 1
 $ :List of 2
  ..$ message: chr "'data' must be of a vector type, was 'NULL'"
  ..$ call   : language matrix(prior$B$mu, length(prior$B$mu), 1)
  ..- attr(*, "class")= chr [1:3] "simpleError" "error" "condition"
NULL
Error in `rownames<-`(`*tmp*`, value = names(res)) :
  attempt to set 'rownames' on an object with no dimensions

**Comment by randel** [comment]
Hi Fatima, thanks for using bMIND. 

Have you already checked the following link? If there is still an error, can you share a replicable dataset and code so that I can test it on my end?
https://github.com/randel/MIND#common-errors

**Comment by 99fatimagr** [comment]
I did check that it's not the common errors. I'm not sure if I can share the dataset for now so will close this issue. If you have any other suggestions to try, please let me know!
