### ISSUE TITLE
Can bMIND use for microarray datasets?

### ISSUE THREAD

**Issue by winkysszhu** [randel/MIND#13]
Many of the datasets I have studied are microarray datasets. Can bMIND use for microarray datasets? Thank you very much.

**Comment by randel** [comment]
Yes, as long as they are in log scale. Thanks!

**Comment by winkysszhu** [comment]
Thanks for the added explanation！I am new to this kind of work and had 2 queries: The output from bMIND, restricting to sufficiently expressed genes (estimated count > 1.0 in 20-40% of individuals).

**Comment by winkysszhu** [comment]
Thanks for the added explanation! I am new to this kind of work and have another question:
How to handle the CTS negative values obtained from bMIND？I am trying to restrict the sufficiently expressed genes for downstream analysis with estimated count > 1.0 in at least 20% of individuals, and replace the remaining counts in the CTS with 0 if they are < 0.
