### ISSUE TITLE
Error in the bmind_de function

### ISSUE THREAD

**Issue by sanderslhc** [randel/MIND#14]
Hi, I'm tseting the pipeline of bMind, however, I have some problem in the process. Briefly, when I am running the bmind_de function, there will be a error named "all connections are in use". I checked the rownames and colnames of frac and bulk files and revised them following your suggestions, but this problem still appeared. Could you give some suggestions about it? Thank you.

**Comment by randel** [comment]
Can you close existing connections? closeAllConnections()
