### ISSUE TITLE
bMIND error using prior: "V is not positive definite for some prior$G/prior$R elements"

### ISSUE THREAD

**Issue by MonalisaHota** [randel/MIND#15]
I am trying to use bMIND with single cell data as prior:
Here is the command
deconv = bMIND(bulk = bulk, frac =frac, profile =prior$profile, covariance = prior$covariance, y = y, ncore = 20)

The tool works fine without prior and also works when I am using  only "profile =prior$profile" without "covariance = prior$covariance". But when I use the prior covariance I get following error:

**[1] "13680 errors"
List of 1
 $ :List of 2
  ..$ message: chr "V is not positive definite for some prior$G/prior$R elements"
  ..$ call   : language priorformat(if (NOpriorG) {     NULL ...
  ..- attr(*, "class")= chr [1:3] "simpleError" "error" "condition"
NULL
Error in mind1[[1]] : subscript out of bounds**

Please let me know if I am doing anything wrong and how to fix this error. Also, use of prior$profile without the prior$covariance, how much impact it will have on the results and are they interpretable?

**Comment by randel** [comment]
Hi Monalisa, thanks for your interest in bMIND. How many donors do you have for single-cell data? The error may be caused by the prior$covariance is not positive definite, which may be common if the number of donors is small. If so, it's ok not to use prior$covariance; just use the prior$profile.

**Comment by MonalisaHota** [comment]
Thanks Randel for your reply. It makes sense. I have 8 donors in the single cell data. That's probably too small.

I still want to keep the donor level variability in my data. So I tried to work around this problem. Let me know if I am doing anything wrong. 

After calculating prior:  **prior = get_prior(sc = ref, meta_sc = ref_meta)** like this. I added a small value to the diagonal for prior$covariance matrix. 

**for (i in 1:dims[1]) {
  diag(prior$covariance[i,,])=diag(prior$covariance[i,,])+0.05
}**
Then checked if the covariance matrices were positive definite:
**gene_pd = apply(prior$covariance, 1, is.positive.definite) 
selected_genes <- names(gene_pd)[gene_pd==TRUE]**

Then only filtered the genes with positive definite covariance matrix. Then I run bMIND with this command:

**deconv = bMIND(bulk = bulk, frac = frac, profile = prior$profile, covariance = prior$covariance, ncore = 20)**

Now the command runs. But I am not sure if I doing the right thing. Does this seem logical to you? Will this approach have big impacts on my results?

**Comment by MonalisaHota** [comment]
This summary of my single cell meta data showing no of cells in each sample
                 **S1   S2    S3   S4   S5    S6     S7  S8**
  **CT1**    32  116  579  496  576  292   35   83
  **CT2**   86  107  292  149    0  370  520  127
  **CT3**   941 2829 3403 1109  742  763   42  884
  **CT4**   318 1069 4820 1152 1684  512   70  487
  **CT5**   355  108   20  632  499  465  508  403
  **CT6**     7   22   68   63    3   74   81   13
  **CT7**   36  172   90  102    9  278  335   33
  **CT8**   225 3994 3318 4782   20 1710 2687 1631

**Comment by randel** [comment]
The number of cells per donor/cell type does not matter much since the covariance is calculated at the donor level. Adding some small diagonal values to the covariance matrix seems to be a good idea, but it has not been tested in simulations.

**Comment by MonalisaHota** [comment]
Thanks so much Randel for your advise. 
I have another naive question. bMIND() conducts a CTS differential expression (DE) analysis if y (case control) is given and provides pval, qval etc. How is that different from the DE analysis done by bmind_de(). I get completely different results when I run these two functions. Am I missing something here? 

This is my understanding of the CTS-DE results from bmind_de()

**coef | the estimated coefficients matrix (gene x variables)** - Provides average CTS expression for cases and controls for each cell type
**qval | the q-values of CTS-DE testing by BH FDR adjustment (gene x cell type).**  - Provides statistical significance of a gene differentially expressed between cases and controls with in a cell type.

bMIND() also provides results in similar format except it does not provide the "coef" but provides the sample level expression matrices.  Is that correct interpretation?

**Comment by randel** [comment]
The `y` in `bMIND()` is a defunct option and may be removed later. For CTS-DE, it's recommended to use `bmind_de()`. `bMIND()` is designed to estimate cell type-specific gene expression.

**Comment by MonalisaHota** [comment]
Got it! Thanks so much.
