### ISSUE TITLE
得到结果后的可视化

### ISSUE THREAD

**Issue by JJJelly77** [randel/MIND#16]
当我得到一个含有四个元素的list: deconv1,我应该怎么对特定基因进行可视化，可以分享一些代码吗

**Comment by randel** [comment]
`deconv1$A` will be a gene x cell type x sample array. You can use `deconv1$A[,1,]` to extract the gene expression profile for the first cell type. For more details, you can check the reference.
https://randel.github.io/MIND/reference/bMIND.html
