### ISSUE TITLE
bmind_de

### ISSUE THREAD

**Issue by bsb2014** [randel/MIND#19]
I have two questions regarding the bmind_de analysis:

deconv = bmind_de(bulk, frac, y = y, covariate = covariate, covariate_bulk = 'c1', covariate_cts = 'c2', np = T)

1. What type of bulk RNA-seq data should be used for the bulk input in the analysis? Should it be TPM, CPM, or raw counts?

2. If the cell-type-specific (CTS) expression is derived from bulk data, should the covariate_bulk and covariate_cts be the same, or can they differ?

Thanks!

**Comment by randel** [comment]
1. We recommend using log TPM or CPM, with bulk and sc data in the same scale.
2. covariate_bulk is the same for all cell types, but covariate_cts vary by cell type.

**Comment by bsb2014** [comment]
I am using the following script for CTS-DEG:

deconv = bmind_de(bulk, frac, y = y, covariate = covariate, covariate_bulk = 'c1', covariate_cts = 'c2', np = TRUE)

Where:
bulk is my bulk TPM data. (my max(tpm)>50, so the bmind will automatically transform these values)
frac is derived from another deconvolution method.

I want to perform CTS-DEG with the covariates for age and sex. In this case, should I use covariate_bulk or covariate_cts for these covariates?

Thanks!

**Comment by bsb2014** [comment]
The frac is derived from another deconvolution method with the same bulk TPM data.

**Comment by randel** [comment]
covariate_bulk affects bulk data, and covariate_cts affects cell type-specific expression. They correspond to c1 and c2 in equation 1 in the paper, respectively. Depending on your sample size, I suggest setting them as covariate_bulk first. If you have a large bulk sample size, you may consider allowing interactions between covariates and W (cell fractions).
https://genome.cshlp.org/content/31/10/1807.full.pdf
