### ISSUE TITLE
interpreting negative CTS expression estimates from mind() function

### ISSUE THREAD

**Issue by bkinnersley** [randel/MIND#3]
Hello,

Firstly thank you for a very interesting paper, method and package! I just had a quick question about the units for output estimates of cell-type specific (CTS) gene expression after applying the mind() function? e.g. in Fig.4C of your paper (https://academic.oup.com/bioinformatics/article/36/3/782/5545976) some of the CTS estimates were negative, and how we should interpret this?

Thanks very much

**Comment by randel** [comment]
Hi! Thanks for your interest in our method! Negative values basically mean very low expression levels, and they are caused by the normality assumption. You may try our new bMIND() function, in which we constrained the CTS estimates by the bulk expression level of each gene.

**Comment by bkinnersley** [comment]
Hi, Thank you very much for the fast response! I am interested in obtaining brain CTS in order to carry out eQTL analysis through making use of the 13 GTEx brain tissue datasets, as outlined in your "MIND" paper and "est_frac" tutorial. For this would you also recommend running bMIND for each individual "bulk" brain tissue to obtain per-tissue CTS expression estimates which could be averaged over each brain tissue - have you found this would give comparable/superior results to the mind() function?

Thanks very much

**Comment by randel** [comment]
One concern on averaging over brain regions is that it ignores the region heterogeneity. In a new preprint with the link below, we calculated CTS eQTLs for 11 brain regions using GTEx V8 data, averaging the two replicates for the frontal cortex and cerebellum, respectively. You can see details in the manuscript, and the second link deposits the significant regional-specific CTS eQTLs.
https://doi.org/10.1101/2020.08.05.238949
https://github.com/randel/bMIND_GTEx8_signif_region_CTS_eQTLs_cis
